// <auto-generated />
using System;
using AgendaPics.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgendaPics.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226010018_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgendaPics.Domain.Entities.Agendamento", b =>
                {
                    b.Property<int>("IdAgendamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAgendamento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAgendamento"));

                    b.Property<string>("CpfPaciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cpfPaciente");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCriacao");

                    b.Property<DateTime>("DataNascimentoPaciente")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataNascimentoPaciente");

                    b.Property<string>("EmailPaciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emailPaciente");

                    b.Property<byte>("GeneroPaciente")
                        .HasColumnType("tinyint")
                        .HasColumnName("generoPaciente");

                    b.Property<byte>("GrauAnsiedadePaciente")
                        .HasColumnType("tinyint")
                        .HasColumnName("grauAnsiedadePaciente");

                    b.Property<int>("IdCidadePaciente")
                        .HasColumnType("int")
                        .HasColumnName("idCidadePaciente");

                    b.Property<short>("IdEstadoPaciente")
                        .HasColumnType("smallint")
                        .HasColumnName("idEstadoPaciente");

                    b.Property<int>("IdInstituicao")
                        .HasColumnType("int")
                        .HasColumnName("idInstituicao");

                    b.Property<short>("IdPratica")
                        .HasColumnType("smallint")
                        .HasColumnName("idPratica");

                    b.Property<string>("NomePaciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nomePaciente");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observacao");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<string>("TelefonePaciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefonePaciente");

                    b.HasKey("IdAgendamento");

                    b.HasIndex("IdInstituicao");

                    b.HasIndex("IdPratica");

                    b.ToTable("Agendamento", (string)null);
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Atendimento", b =>
                {
                    b.Property<int>("IdAtendimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAtendimento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAtendimento"));

                    b.Property<DateTime>("DataAtendimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAtendimento");

                    b.Property<int>("IdAgendamento")
                        .HasColumnType("int")
                        .HasColumnName("idAgendamento");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observacao");

                    b.Property<string>("QueixaPaciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("queixaPaciente");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("IdAtendimento");

                    b.HasIndex("IdAgendamento");

                    b.ToTable("Atendimento", (string)null);
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Avaliacao", b =>
                {
                    b.Property<int>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAvaliacao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvaliacao"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("data");

                    b.Property<int>("IdAtendimento")
                        .HasColumnType("int")
                        .HasColumnName("idAtendimento");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("link");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observacao");

                    b.HasKey("IdAvaliacao");

                    b.HasIndex("IdAtendimento");

                    b.ToTable("Avaliacao", (string)null);
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Cidade", b =>
                {
                    b.Property<int>("IdCidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCidade");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCidade"));

                    b.Property<short>("IdEstado")
                        .HasColumnType("smallint")
                        .HasColumnName("idEstado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.HasKey("IdCidade");

                    b.HasIndex("IdEstado");

                    b.ToTable("Cidade", (string)null);

                    b.HasData(
                        new
                        {
                            IdCidade = 1100205,
                            IdEstado = (short)11,
                            Nome = "Porto Velho"
                        },
                        new
                        {
                            IdCidade = 1100122,
                            IdEstado = (short)11,
                            Nome = "Ji-Paraná"
                        },
                        new
                        {
                            IdCidade = 1100023,
                            IdEstado = (short)11,
                            Nome = "Ariquemes"
                        },
                        new
                        {
                            IdCidade = 1100304,
                            IdEstado = (short)11,
                            Nome = "Vilhena"
                        },
                        new
                        {
                            IdCidade = 1100049,
                            IdEstado = (short)11,
                            Nome = "Cacoal"
                        },
                        new
                        {
                            IdCidade = 1100288,
                            IdEstado = (short)11,
                            Nome = "Rolim de Moura"
                        },
                        new
                        {
                            IdCidade = 1100114,
                            IdEstado = (short)11,
                            Nome = "Jaru"
                        },
                        new
                        {
                            IdCidade = 1100106,
                            IdEstado = (short)11,
                            Nome = "Guajará-Mirim"
                        },
                        new
                        {
                            IdCidade = 1100189,
                            IdEstado = (short)11,
                            Nome = "Pimenta Bueno"
                        },
                        new
                        {
                            IdCidade = 1100130,
                            IdEstado = (short)11,
                            Nome = "Machadinho d'Oeste"
                        },
                        new
                        {
                            IdCidade = 1200401,
                            IdEstado = (short)12,
                            Nome = "Rio Branco"
                        },
                        new
                        {
                            IdCidade = 1200203,
                            IdEstado = (short)12,
                            Nome = "Cruzeiro do Sul"
                        },
                        new
                        {
                            IdCidade = 1200500,
                            IdEstado = (short)12,
                            Nome = "Sena Madureira"
                        },
                        new
                        {
                            IdCidade = 1200609,
                            IdEstado = (short)12,
                            Nome = "Tarauacá"
                        },
                        new
                        {
                            IdCidade = 1200302,
                            IdEstado = (short)12,
                            Nome = "Feijó"
                        },
                        new
                        {
                            IdCidade = 1200104,
                            IdEstado = (short)12,
                            Nome = "Brasileia"
                        },
                        new
                        {
                            IdCidade = 1200252,
                            IdEstado = (short)12,
                            Nome = "Epitaciolândia"
                        },
                        new
                        {
                            IdCidade = 1200708,
                            IdEstado = (short)12,
                            Nome = "Xapuri"
                        },
                        new
                        {
                            IdCidade = 1200385,
                            IdEstado = (short)12,
                            Nome = "Plácido de Castro"
                        },
                        new
                        {
                            IdCidade = 1200450,
                            IdEstado = (short)12,
                            Nome = "Senador Guiomard"
                        },
                        new
                        {
                            IdCidade = 1302603,
                            IdEstado = (short)13,
                            Nome = "Manaus"
                        },
                        new
                        {
                            IdCidade = 1303403,
                            IdEstado = (short)13,
                            Nome = "Parintins"
                        },
                        new
                        {
                            IdCidade = 1301902,
                            IdEstado = (short)13,
                            Nome = "Itacoatiara"
                        },
                        new
                        {
                            IdCidade = 1302504,
                            IdEstado = (short)13,
                            Nome = "Manacapuru"
                        },
                        new
                        {
                            IdCidade = 1301209,
                            IdEstado = (short)13,
                            Nome = "Coari"
                        },
                        new
                        {
                            IdCidade = 1304203,
                            IdEstado = (short)13,
                            Nome = "Tefé"
                        },
                        new
                        {
                            IdCidade = 1302900,
                            IdEstado = (short)13,
                            Nome = "Maués"
                        },
                        new
                        {
                            IdCidade = 1301852,
                            IdEstado = (short)13,
                            Nome = "Iranduba"
                        },
                        new
                        {
                            IdCidade = 1304062,
                            IdEstado = (short)13,
                            Nome = "Tabatinga"
                        },
                        new
                        {
                            IdCidade = 1301704,
                            IdEstado = (short)13,
                            Nome = "Humaitá"
                        },
                        new
                        {
                            IdCidade = 1400100,
                            IdEstado = (short)14,
                            Nome = "Boa Vista"
                        },
                        new
                        {
                            IdCidade = 1400472,
                            IdEstado = (short)14,
                            Nome = "Rorainópolis"
                        },
                        new
                        {
                            IdCidade = 1400209,
                            IdEstado = (short)14,
                            Nome = "Caracaraí"
                        },
                        new
                        {
                            IdCidade = 1400050,
                            IdEstado = (short)14,
                            Nome = "Alto Alegre"
                        },
                        new
                        {
                            IdCidade = 1400308,
                            IdEstado = (short)14,
                            Nome = "Mucajaí"
                        },
                        new
                        {
                            IdCidade = 1400456,
                            IdEstado = (short)14,
                            Nome = "Pacaraima"
                        },
                        new
                        {
                            IdCidade = 1400175,
                            IdEstado = (short)14,
                            Nome = "Cantá"
                        },
                        new
                        {
                            IdCidade = 1400159,
                            IdEstado = (short)14,
                            Nome = "Bonfim"
                        },
                        new
                        {
                            IdCidade = 1400027,
                            IdEstado = (short)14,
                            Nome = "Amajari"
                        },
                        new
                        {
                            IdCidade = 1400282,
                            IdEstado = (short)14,
                            Nome = "Iracema"
                        },
                        new
                        {
                            IdCidade = 1501402,
                            IdEstado = (short)15,
                            Nome = "Belém"
                        },
                        new
                        {
                            IdCidade = 1500859,
                            IdEstado = (short)15,
                            Nome = "Ananindeua"
                        },
                        new
                        {
                            IdCidade = 1507204,
                            IdEstado = (short)15,
                            Nome = "Santarém"
                        },
                        new
                        {
                            IdCidade = 1504208,
                            IdEstado = (short)15,
                            Nome = "Marabá"
                        },
                        new
                        {
                            IdCidade = 1505536,
                            IdEstado = (short)15,
                            Nome = "Parauapebas"
                        },
                        new
                        {
                            IdCidade = 1502400,
                            IdEstado = (short)15,
                            Nome = "Castanhal"
                        },
                        new
                        {
                            IdCidade = 1500107,
                            IdEstado = (short)15,
                            Nome = "Abaetetuba"
                        },
                        new
                        {
                            IdCidade = 1502103,
                            IdEstado = (short)15,
                            Nome = "Cametá"
                        },
                        new
                        {
                            IdCidade = 1500602,
                            IdEstado = (short)15,
                            Nome = "Altamira"
                        },
                        new
                        {
                            IdCidade = 1503606,
                            IdEstado = (short)15,
                            Nome = "Itaituba"
                        },
                        new
                        {
                            IdCidade = 1600303,
                            IdEstado = (short)16,
                            Nome = "Macapá"
                        },
                        new
                        {
                            IdCidade = 1600600,
                            IdEstado = (short)16,
                            Nome = "Santana"
                        },
                        new
                        {
                            IdCidade = 1600279,
                            IdEstado = (short)16,
                            Nome = "Laranjal do Jari"
                        },
                        new
                        {
                            IdCidade = 1600501,
                            IdEstado = (short)16,
                            Nome = "Oiapoque"
                        },
                        new
                        {
                            IdCidade = 1600402,
                            IdEstado = (short)16,
                            Nome = "Mazagão"
                        },
                        new
                        {
                            IdCidade = 1600535,
                            IdEstado = (short)16,
                            Nome = "Porto Grande"
                        },
                        new
                        {
                            IdCidade = 1600057,
                            IdEstado = (short)16,
                            Nome = "Pedra Branca do Amapari"
                        },
                        new
                        {
                            IdCidade = 1600808,
                            IdEstado = (short)16,
                            Nome = "Vitória do Jari"
                        },
                        new
                        {
                            IdCidade = 1600204,
                            IdEstado = (short)16,
                            Nome = "Calçoene"
                        },
                        new
                        {
                            IdCidade = 1600709,
                            IdEstado = (short)16,
                            Nome = "Tartarugalzinho"
                        },
                        new
                        {
                            IdCidade = 1721000,
                            IdEstado = (short)17,
                            Nome = "Palmas"
                        },
                        new
                        {
                            IdCidade = 1702109,
                            IdEstado = (short)17,
                            Nome = "Araguaína"
                        },
                        new
                        {
                            IdCidade = 1709500,
                            IdEstado = (short)17,
                            Nome = "Gurupi"
                        },
                        new
                        {
                            IdCidade = 1718204,
                            IdEstado = (short)17,
                            Nome = "Porto Nacional"
                        },
                        new
                        {
                            IdCidade = 1716109,
                            IdEstado = (short)17,
                            Nome = "Paraíso do Tocantins"
                        },
                        new
                        {
                            IdCidade = 1716802,
                            IdEstado = (short)17,
                            Nome = "Colinas do Tocantins"
                        },
                        new
                        {
                            IdCidade = 1709302,
                            IdEstado = (short)17,
                            Nome = "Guaraí"
                        },
                        new
                        {
                            IdCidade = 1721109,
                            IdEstado = (short)17,
                            Nome = "Tocantinópolis"
                        },
                        new
                        {
                            IdCidade = 1713205,
                            IdEstado = (short)17,
                            Nome = "Miracema do Tocantins"
                        },
                        new
                        {
                            IdCidade = 1702703,
                            IdEstado = (short)17,
                            Nome = "Araguatins"
                        },
                        new
                        {
                            IdCidade = 2111300,
                            IdEstado = (short)21,
                            Nome = "São Luís"
                        },
                        new
                        {
                            IdCidade = 2105302,
                            IdEstado = (short)21,
                            Nome = "Imperatriz"
                        },
                        new
                        {
                            IdCidade = 2111201,
                            IdEstado = (short)21,
                            Nome = "São José de Ribamar"
                        },
                        new
                        {
                            IdCidade = 2112209,
                            IdEstado = (short)21,
                            Nome = "Timon"
                        },
                        new
                        {
                            IdCidade = 2103000,
                            IdEstado = (short)21,
                            Nome = "Caxias"
                        },
                        new
                        {
                            IdCidade = 2103307,
                            IdEstado = (short)21,
                            Nome = "Codó"
                        },
                        new
                        {
                            IdCidade = 2107800,
                            IdEstado = (short)21,
                            Nome = "Paço do Lumiar"
                        },
                        new
                        {
                            IdCidade = 2100055,
                            IdEstado = (short)21,
                            Nome = "Açailândia"
                        },
                        new
                        {
                            IdCidade = 2101202,
                            IdEstado = (short)21,
                            Nome = "Bacabal"
                        },
                        new
                        {
                            IdCidade = 2101400,
                            IdEstado = (short)21,
                            Nome = "Balsas"
                        },
                        new
                        {
                            IdCidade = 2211001,
                            IdEstado = (short)22,
                            Nome = "Teresina"
                        },
                        new
                        {
                            IdCidade = 2207702,
                            IdEstado = (short)22,
                            Nome = "Parnaíba"
                        },
                        new
                        {
                            IdCidade = 2208007,
                            IdEstado = (short)22,
                            Nome = "Picos"
                        },
                        new
                        {
                            IdCidade = 2208304,
                            IdEstado = (short)22,
                            Nome = "Piripiri"
                        },
                        new
                        {
                            IdCidade = 2203909,
                            IdEstado = (short)22,
                            Nome = "Floriano"
                        },
                        new
                        {
                            IdCidade = 2202208,
                            IdEstado = (short)22,
                            Nome = "Campo Maior"
                        },
                        new
                        {
                            IdCidade = 2201200,
                            IdEstado = (short)22,
                            Nome = "Barras"
                        },
                        new
                        {
                            IdCidade = 2211100,
                            IdEstado = (short)22,
                            Nome = "União"
                        },
                        new
                        {
                            IdCidade = 2200400,
                            IdEstado = (short)22,
                            Nome = "Altos"
                        },
                        new
                        {
                            IdCidade = 2205508,
                            IdEstado = (short)22,
                            Nome = "José de Freitas"
                        },
                        new
                        {
                            IdCidade = 2304400,
                            IdEstado = (short)23,
                            Nome = "Fortaleza"
                        },
                        new
                        {
                            IdCidade = 2303709,
                            IdEstado = (short)23,
                            Nome = "Caucaia"
                        },
                        new
                        {
                            IdCidade = 2307304,
                            IdEstado = (short)23,
                            Nome = "Juazeiro do Norte"
                        },
                        new
                        {
                            IdCidade = 2307650,
                            IdEstado = (short)23,
                            Nome = "Maracanaú"
                        },
                        new
                        {
                            IdCidade = 2312908,
                            IdEstado = (short)23,
                            Nome = "Sobral"
                        },
                        new
                        {
                            IdCidade = 2304202,
                            IdEstado = (short)23,
                            Nome = "Crato"
                        },
                        new
                        {
                            IdCidade = 2306405,
                            IdEstado = (short)23,
                            Nome = "Itapipoca"
                        },
                        new
                        {
                            IdCidade = 2307700,
                            IdEstado = (short)23,
                            Nome = "Maranguape"
                        },
                        new
                        {
                            IdCidade = 2305506,
                            IdEstado = (short)23,
                            Nome = "Iguatu"
                        },
                        new
                        {
                            IdCidade = 2311306,
                            IdEstado = (short)23,
                            Nome = "Quixadá"
                        },
                        new
                        {
                            IdCidade = 2408102,
                            IdEstado = (short)24,
                            Nome = "Natal"
                        },
                        new
                        {
                            IdCidade = 2408003,
                            IdEstado = (short)24,
                            Nome = "Mossoró"
                        },
                        new
                        {
                            IdCidade = 2403251,
                            IdEstado = (short)24,
                            Nome = "Parnamirim"
                        },
                        new
                        {
                            IdCidade = 2412005,
                            IdEstado = (short)24,
                            Nome = "São Gonçalo do Amarante"
                        },
                        new
                        {
                            IdCidade = 2402006,
                            IdEstado = (short)24,
                            Nome = "Caicó"
                        },
                        new
                        {
                            IdCidade = 2400109,
                            IdEstado = (short)24,
                            Nome = "Açu"
                        },
                        new
                        {
                            IdCidade = 2402600,
                            IdEstado = (short)24,
                            Nome = "Ceará-Mirim"
                        },
                        new
                        {
                            IdCidade = 2412203,
                            IdEstado = (short)24,
                            Nome = "São José de Mipibu"
                        },
                        new
                        {
                            IdCidade = 2403103,
                            IdEstado = (short)24,
                            Nome = "Currais Novos"
                        },
                        new
                        {
                            IdCidade = 2411403,
                            IdEstado = (short)24,
                            Nome = "Santa Cruz"
                        },
                        new
                        {
                            IdCidade = 2507507,
                            IdEstado = (short)25,
                            Nome = "João Pessoa"
                        },
                        new
                        {
                            IdCidade = 2504009,
                            IdEstado = (short)25,
                            Nome = "Campina Grande"
                        },
                        new
                        {
                            IdCidade = 2513703,
                            IdEstado = (short)25,
                            Nome = "Santa Rita"
                        },
                        new
                        {
                            IdCidade = 2510808,
                            IdEstado = (short)25,
                            Nome = "Patos"
                        },
                        new
                        {
                            IdCidade = 2502003,
                            IdEstado = (short)25,
                            Nome = "Bayeux"
                        },
                        new
                        {
                            IdCidade = 2516201,
                            IdEstado = (short)25,
                            Nome = "Sousa"
                        },
                        new
                        {
                            IdCidade = 2503704,
                            IdEstado = (short)25,
                            Nome = "Cajazeiras"
                        },
                        new
                        {
                            IdCidade = 2503209,
                            IdEstado = (short)25,
                            Nome = "Cabedelo"
                        },
                        new
                        {
                            IdCidade = 2505501,
                            IdEstado = (short)25,
                            Nome = "Guarabira"
                        },
                        new
                        {
                            IdCidade = 2515302,
                            IdEstado = (short)25,
                            Nome = "Sapé"
                        },
                        new
                        {
                            IdCidade = 2611606,
                            IdEstado = (short)26,
                            Nome = "Recife"
                        },
                        new
                        {
                            IdCidade = 2607901,
                            IdEstado = (short)26,
                            Nome = "Jaboatão dos Guararapes"
                        },
                        new
                        {
                            IdCidade = 2609600,
                            IdEstado = (short)26,
                            Nome = "Olinda"
                        },
                        new
                        {
                            IdCidade = 2604106,
                            IdEstado = (short)26,
                            Nome = "Caruaru"
                        },
                        new
                        {
                            IdCidade = 2611101,
                            IdEstado = (short)26,
                            Nome = "Petrolina"
                        },
                        new
                        {
                            IdCidade = 2610707,
                            IdEstado = (short)26,
                            Nome = "Paulista"
                        },
                        new
                        {
                            IdCidade = 2606002,
                            IdEstado = (short)26,
                            Nome = "Garanhuns"
                        },
                        new
                        {
                            IdCidade = 2616407,
                            IdEstado = (short)26,
                            Nome = "Vitória de Santo Antão"
                        },
                        new
                        {
                            IdCidade = 2606804,
                            IdEstado = (short)26,
                            Nome = "Igarassu"
                        },
                        new
                        {
                            IdCidade = 2612208,
                            IdEstado = (short)26,
                            Nome = "Ribeirão"
                        },
                        new
                        {
                            IdCidade = 2704302,
                            IdEstado = (short)27,
                            Nome = "Maceió"
                        },
                        new
                        {
                            IdCidade = 2700300,
                            IdEstado = (short)27,
                            Nome = "Arapiraca"
                        },
                        new
                        {
                            IdCidade = 2707701,
                            IdEstado = (short)27,
                            Nome = "Rio Largo"
                        },
                        new
                        {
                            IdCidade = 2706101,
                            IdEstado = (short)27,
                            Nome = "Palmeira dos Índios"
                        },
                        new
                        {
                            IdCidade = 2706703,
                            IdEstado = (short)27,
                            Nome = "Penedo"
                        },
                        new
                        {
                            IdCidade = 2709103,
                            IdEstado = (short)27,
                            Nome = "União dos Palmares"
                        },
                        new
                        {
                            IdCidade = 2708303,
                            IdEstado = (short)27,
                            Nome = "Santana do Ipanema"
                        },
                        new
                        {
                            IdCidade = 2702405,
                            IdEstado = (short)27,
                            Nome = "Delmiro Gouveia"
                        },
                        new
                        {
                            IdCidade = 2708600,
                            IdEstado = (short)27,
                            Nome = "São Miguel dos Campos"
                        },
                        new
                        {
                            IdCidade = 2702306,
                            IdEstado = (short)27,
                            Nome = "Coruripe"
                        },
                        new
                        {
                            IdCidade = 2800308,
                            IdEstado = (short)28,
                            Nome = "Aracaju"
                        },
                        new
                        {
                            IdCidade = 2804508,
                            IdEstado = (short)28,
                            Nome = "Nossa Senhora do Socorro"
                        },
                        new
                        {
                            IdCidade = 2803500,
                            IdEstado = (short)28,
                            Nome = "Lagarto"
                        },
                        new
                        {
                            IdCidade = 2802908,
                            IdEstado = (short)28,
                            Nome = "Itabaiana"
                        },
                        new
                        {
                            IdCidade = 2802106,
                            IdEstado = (short)28,
                            Nome = "Estância"
                        },
                        new
                        {
                            IdCidade = 2806701,
                            IdEstado = (short)28,
                            Nome = "São Cristóvão"
                        },
                        new
                        {
                            IdCidade = 2804409,
                            IdEstado = (short)28,
                            Nome = "Nossa Senhora das Dores"
                        },
                        new
                        {
                            IdCidade = 2807402,
                            IdEstado = (short)28,
                            Nome = "Tobias Barreto"
                        },
                        new
                        {
                            IdCidade = 2807105,
                            IdEstado = (short)28,
                            Nome = "Simão Dias"
                        },
                        new
                        {
                            IdCidade = 2805406,
                            IdEstado = (short)28,
                            Nome = "Propriá"
                        },
                        new
                        {
                            IdCidade = 2927408,
                            IdEstado = (short)29,
                            Nome = "Salvador"
                        },
                        new
                        {
                            IdCidade = 2910800,
                            IdEstado = (short)29,
                            Nome = "Feira de Santana"
                        },
                        new
                        {
                            IdCidade = 2933307,
                            IdEstado = (short)29,
                            Nome = "Vitória da Conquista"
                        },
                        new
                        {
                            IdCidade = 2905701,
                            IdEstado = (short)29,
                            Nome = "Camaçari"
                        },
                        new
                        {
                            IdCidade = 2918407,
                            IdEstado = (short)29,
                            Nome = "Juazeiro"
                        },
                        new
                        {
                            IdCidade = 2914802,
                            IdEstado = (short)29,
                            Nome = "Itabuna"
                        },
                        new
                        {
                            IdCidade = 2919207,
                            IdEstado = (short)29,
                            Nome = "Lauro de Freitas"
                        },
                        new
                        {
                            IdCidade = 2913606,
                            IdEstado = (short)29,
                            Nome = "Ilhéus"
                        },
                        new
                        {
                            IdCidade = 2917903,
                            IdEstado = (short)29,
                            Nome = "Jequié"
                        },
                        new
                        {
                            IdCidade = 2931350,
                            IdEstado = (short)29,
                            Nome = "Teixeira de Freitas"
                        },
                        new
                        {
                            IdCidade = 3106200,
                            IdEstado = (short)31,
                            Nome = "Belo Horizonte"
                        },
                        new
                        {
                            IdCidade = 3170206,
                            IdEstado = (short)31,
                            Nome = "Uberlândia"
                        },
                        new
                        {
                            IdCidade = 3118601,
                            IdEstado = (short)31,
                            Nome = "Contagem"
                        },
                        new
                        {
                            IdCidade = 3136702,
                            IdEstado = (short)31,
                            Nome = "Juiz de Fora"
                        },
                        new
                        {
                            IdCidade = 3106705,
                            IdEstado = (short)31,
                            Nome = "Betim"
                        },
                        new
                        {
                            IdCidade = 3143302,
                            IdEstado = (short)31,
                            Nome = "Montes Claros"
                        },
                        new
                        {
                            IdCidade = 3154606,
                            IdEstado = (short)31,
                            Nome = "Ribeirão das Neves"
                        },
                        new
                        {
                            IdCidade = 3170107,
                            IdEstado = (short)31,
                            Nome = "Uberaba"
                        },
                        new
                        {
                            IdCidade = 3127701,
                            IdEstado = (short)31,
                            Nome = "Governador Valadares"
                        },
                        new
                        {
                            IdCidade = 3131307,
                            IdEstado = (short)31,
                            Nome = "Ipatinga"
                        },
                        new
                        {
                            IdCidade = 3143104,
                            IdEstado = (short)31,
                            Nome = "Monte Carmelo"
                        },
                        new
                        {
                            IdCidade = 3205200,
                            IdEstado = (short)32,
                            Nome = "Vila Velha"
                        },
                        new
                        {
                            IdCidade = 3205010,
                            IdEstado = (short)32,
                            Nome = "Serra"
                        },
                        new
                        {
                            IdCidade = 3201308,
                            IdEstado = (short)32,
                            Nome = "Cariacica"
                        },
                        new
                        {
                            IdCidade = 3205309,
                            IdEstado = (short)32,
                            Nome = "Vitória"
                        },
                        new
                        {
                            IdCidade = 3201209,
                            IdEstado = (short)32,
                            Nome = "Cachoeiro de Itapemirim"
                        },
                        new
                        {
                            IdCidade = 3203205,
                            IdEstado = (short)32,
                            Nome = "Linhares"
                        },
                        new
                        {
                            IdCidade = 3204906,
                            IdEstado = (short)32,
                            Nome = "São Mateus"
                        },
                        new
                        {
                            IdCidade = 3201506,
                            IdEstado = (short)32,
                            Nome = "Colatina"
                        },
                        new
                        {
                            IdCidade = 3202405,
                            IdEstado = (short)32,
                            Nome = "Guarapari"
                        },
                        new
                        {
                            IdCidade = 3200607,
                            IdEstado = (short)32,
                            Nome = "Aracruz"
                        },
                        new
                        {
                            IdCidade = 3304557,
                            IdEstado = (short)33,
                            Nome = "Rio de Janeiro"
                        },
                        new
                        {
                            IdCidade = 3304904,
                            IdEstado = (short)33,
                            Nome = "São Gonçalo"
                        },
                        new
                        {
                            IdCidade = 3301702,
                            IdEstado = (short)33,
                            Nome = "Duque de Caxias"
                        },
                        new
                        {
                            IdCidade = 3303500,
                            IdEstado = (short)33,
                            Nome = "Nova Iguaçu"
                        },
                        new
                        {
                            IdCidade = 3300456,
                            IdEstado = (short)33,
                            Nome = "Belford Roxo"
                        },
                        new
                        {
                            IdCidade = 3303302,
                            IdEstado = (short)33,
                            Nome = "Niterói"
                        },
                        new
                        {
                            IdCidade = 3301009,
                            IdEstado = (short)33,
                            Nome = "Campos dos Goytacazes"
                        },
                        new
                        {
                            IdCidade = 3305109,
                            IdEstado = (short)33,
                            Nome = "São João de Meriti"
                        },
                        new
                        {
                            IdCidade = 3303906,
                            IdEstado = (short)33,
                            Nome = "Petrópolis"
                        },
                        new
                        {
                            IdCidade = 3306701,
                            IdEstado = (short)33,
                            Nome = "Volta Redonda"
                        },
                        new
                        {
                            IdCidade = 3550308,
                            IdEstado = (short)35,
                            Nome = "São Paulo"
                        },
                        new
                        {
                            IdCidade = 3518800,
                            IdEstado = (short)35,
                            Nome = "Guarulhos"
                        },
                        new
                        {
                            IdCidade = 3509502,
                            IdEstado = (short)35,
                            Nome = "Campinas"
                        },
                        new
                        {
                            IdCidade = 3548708,
                            IdEstado = (short)35,
                            Nome = "São Bernardo do Campo"
                        },
                        new
                        {
                            IdCidade = 3547809,
                            IdEstado = (short)35,
                            Nome = "Santo André"
                        },
                        new
                        {
                            IdCidade = 3534401,
                            IdEstado = (short)35,
                            Nome = "Osasco"
                        },
                        new
                        {
                            IdCidade = 3543402,
                            IdEstado = (short)35,
                            Nome = "Ribeirão Preto"
                        },
                        new
                        {
                            IdCidade = 3552205,
                            IdEstado = (short)35,
                            Nome = "Sorocaba"
                        },
                        new
                        {
                            IdCidade = 3529401,
                            IdEstado = (short)35,
                            Nome = "Mauá"
                        },
                        new
                        {
                            IdCidade = 3549904,
                            IdEstado = (short)35,
                            Nome = "São José dos Campos"
                        },
                        new
                        {
                            IdCidade = 4106902,
                            IdEstado = (short)41,
                            Nome = "Curitiba"
                        },
                        new
                        {
                            IdCidade = 4113700,
                            IdEstado = (short)41,
                            Nome = "Londrina"
                        },
                        new
                        {
                            IdCidade = 4115200,
                            IdEstado = (short)41,
                            Nome = "Maringá"
                        },
                        new
                        {
                            IdCidade = 4119905,
                            IdEstado = (short)41,
                            Nome = "Ponta Grossa"
                        },
                        new
                        {
                            IdCidade = 4104808,
                            IdEstado = (short)41,
                            Nome = "Cascavel"
                        },
                        new
                        {
                            IdCidade = 4125506,
                            IdEstado = (short)41,
                            Nome = "São José dos Pinhais"
                        },
                        new
                        {
                            IdCidade = 4105805,
                            IdEstado = (short)41,
                            Nome = "Colombo"
                        },
                        new
                        {
                            IdCidade = 4108304,
                            IdEstado = (short)41,
                            Nome = "Foz do Iguaçu"
                        },
                        new
                        {
                            IdCidade = 4109401,
                            IdEstado = (short)41,
                            Nome = "Guarapuava"
                        },
                        new
                        {
                            IdCidade = 4118204,
                            IdEstado = (short)41,
                            Nome = "Paranaguá"
                        },
                        new
                        {
                            IdCidade = 4209102,
                            IdEstado = (short)42,
                            Nome = "Joinville"
                        },
                        new
                        {
                            IdCidade = 4205407,
                            IdEstado = (short)42,
                            Nome = "Florianópolis"
                        },
                        new
                        {
                            IdCidade = 4202404,
                            IdEstado = (short)42,
                            Nome = "Blumenau"
                        },
                        new
                        {
                            IdCidade = 4216602,
                            IdEstado = (short)42,
                            Nome = "São José"
                        },
                        new
                        {
                            IdCidade = 4204202,
                            IdEstado = (short)42,
                            Nome = "Chapecó"
                        },
                        new
                        {
                            IdCidade = 4204608,
                            IdEstado = (short)42,
                            Nome = "Criciúma"
                        },
                        new
                        {
                            IdCidade = 4208203,
                            IdEstado = (short)42,
                            Nome = "Itajaí"
                        },
                        new
                        {
                            IdCidade = 4208906,
                            IdEstado = (short)42,
                            Nome = "Jaraguá do Sul"
                        },
                        new
                        {
                            IdCidade = 4211900,
                            IdEstado = (short)42,
                            Nome = "Palhoça"
                        },
                        new
                        {
                            IdCidade = 4202008,
                            IdEstado = (short)42,
                            Nome = "Balneário Camboriú"
                        },
                        new
                        {
                            IdCidade = 4314902,
                            IdEstado = (short)43,
                            Nome = "Porto Alegre"
                        },
                        new
                        {
                            IdCidade = 4305108,
                            IdEstado = (short)43,
                            Nome = "Caxias do Sul"
                        },
                        new
                        {
                            IdCidade = 4314100,
                            IdEstado = (short)43,
                            Nome = "Pelotas"
                        },
                        new
                        {
                            IdCidade = 4304606,
                            IdEstado = (short)43,
                            Nome = "Canoas"
                        },
                        new
                        {
                            IdCidade = 4316907,
                            IdEstado = (short)43,
                            Nome = "Santa Maria"
                        },
                        new
                        {
                            IdCidade = 4309209,
                            IdEstado = (short)43,
                            Nome = "Gravataí"
                        },
                        new
                        {
                            IdCidade = 4323002,
                            IdEstado = (short)43,
                            Nome = "Viamão"
                        },
                        new
                        {
                            IdCidade = 4313409,
                            IdEstado = (short)43,
                            Nome = "Novo Hamburgo"
                        },
                        new
                        {
                            IdCidade = 4318705,
                            IdEstado = (short)43,
                            Nome = "São Leopoldo"
                        },
                        new
                        {
                            IdCidade = 4315602,
                            IdEstado = (short)43,
                            Nome = "Rio Grande"
                        },
                        new
                        {
                            IdCidade = 5002704,
                            IdEstado = (short)50,
                            Nome = "Campo Grande"
                        },
                        new
                        {
                            IdCidade = 5003702,
                            IdEstado = (short)50,
                            Nome = "Dourados"
                        },
                        new
                        {
                            IdCidade = 5008305,
                            IdEstado = (short)50,
                            Nome = "Três Lagoas"
                        },
                        new
                        {
                            IdCidade = 5003207,
                            IdEstado = (short)50,
                            Nome = "Corumbá"
                        },
                        new
                        {
                            IdCidade = 5006606,
                            IdEstado = (short)50,
                            Nome = "Ponta Porã"
                        },
                        new
                        {
                            IdCidade = 5005904,
                            IdEstado = (short)50,
                            Nome = "Naviraí"
                        },
                        new
                        {
                            IdCidade = 5006200,
                            IdEstado = (short)50,
                            Nome = "Nova Andradina"
                        },
                        new
                        {
                            IdCidade = 5001102,
                            IdEstado = (short)50,
                            Nome = "Aquidauana"
                        },
                        new
                        {
                            IdCidade = 5007901,
                            IdEstado = (short)50,
                            Nome = "Sidrolândia"
                        },
                        new
                        {
                            IdCidade = 5006309,
                            IdEstado = (short)50,
                            Nome = "Paranaíba"
                        },
                        new
                        {
                            IdCidade = 5103403,
                            IdEstado = (short)51,
                            Nome = "Cuiabá"
                        },
                        new
                        {
                            IdCidade = 5108402,
                            IdEstado = (short)51,
                            Nome = "Várzea Grande"
                        },
                        new
                        {
                            IdCidade = 5107602,
                            IdEstado = (short)51,
                            Nome = "Rondonópolis"
                        },
                        new
                        {
                            IdCidade = 5107909,
                            IdEstado = (short)51,
                            Nome = "Sinop"
                        },
                        new
                        {
                            IdCidade = 5107941,
                            IdEstado = (short)51,
                            Nome = "Tangará da Serra"
                        },
                        new
                        {
                            IdCidade = 5102504,
                            IdEstado = (short)51,
                            Nome = "Cáceres"
                        },
                        new
                        {
                            IdCidade = 5107925,
                            IdEstado = (short)51,
                            Nome = "Sorriso"
                        },
                        new
                        {
                            IdCidade = 5105259,
                            IdEstado = (short)51,
                            Nome = "Lucas do Rio Verde"
                        },
                        new
                        {
                            IdCidade = 5106455,
                            IdEstado = (short)51,
                            Nome = "Primavera do Leste"
                        },
                        new
                        {
                            IdCidade = 5101803,
                            IdEstado = (short)51,
                            Nome = "Barra do Garças"
                        },
                        new
                        {
                            IdCidade = 5208707,
                            IdEstado = (short)52,
                            Nome = "Goiânia"
                        },
                        new
                        {
                            IdCidade = 5201405,
                            IdEstado = (short)52,
                            Nome = "Aparecida de Goiânia"
                        },
                        new
                        {
                            IdCidade = 5201108,
                            IdEstado = (short)52,
                            Nome = "Anápolis"
                        },
                        new
                        {
                            IdCidade = 5218805,
                            IdEstado = (short)52,
                            Nome = "Rio Verde"
                        },
                        new
                        {
                            IdCidade = 5212501,
                            IdEstado = (short)52,
                            Nome = "Luziânia"
                        },
                        new
                        {
                            IdCidade = 5200050,
                            IdEstado = (short)52,
                            Nome = "Águas Lindas de Goiás"
                        },
                        new
                        {
                            IdCidade = 5221858,
                            IdEstado = (short)52,
                            Nome = "Valparaíso de Goiás"
                        },
                        new
                        {
                            IdCidade = 5221403,
                            IdEstado = (short)52,
                            Nome = "Trindade"
                        },
                        new
                        {
                            IdCidade = 5208004,
                            IdEstado = (short)52,
                            Nome = "Formosa"
                        },
                        new
                        {
                            IdCidade = 5215231,
                            IdEstado = (short)52,
                            Nome = "Novo Gama"
                        },
                        new
                        {
                            IdCidade = 5300108,
                            IdEstado = (short)53,
                            Nome = "Brasília"
                        });
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Estado", b =>
                {
                    b.Property<short>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("idEstado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("IdEstado"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sigla");

                    b.HasKey("IdEstado");

                    b.ToTable("Estado", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstado = (short)11,
                            Nome = "Rondônia",
                            Sigla = "RO"
                        },
                        new
                        {
                            IdEstado = (short)12,
                            Nome = "Acre",
                            Sigla = "AC"
                        },
                        new
                        {
                            IdEstado = (short)13,
                            Nome = "Amazonas",
                            Sigla = "AM"
                        },
                        new
                        {
                            IdEstado = (short)14,
                            Nome = "Roraima",
                            Sigla = "RR"
                        },
                        new
                        {
                            IdEstado = (short)15,
                            Nome = "Pará",
                            Sigla = "PA"
                        },
                        new
                        {
                            IdEstado = (short)16,
                            Nome = "Amapá",
                            Sigla = "AP"
                        },
                        new
                        {
                            IdEstado = (short)17,
                            Nome = "Tocantins",
                            Sigla = "TO"
                        },
                        new
                        {
                            IdEstado = (short)21,
                            Nome = "Maranhão",
                            Sigla = "MA"
                        },
                        new
                        {
                            IdEstado = (short)22,
                            Nome = "Piauí",
                            Sigla = "PI"
                        },
                        new
                        {
                            IdEstado = (short)23,
                            Nome = "Ceará",
                            Sigla = "CE"
                        },
                        new
                        {
                            IdEstado = (short)24,
                            Nome = "Rio Grande do Norte",
                            Sigla = "RN"
                        },
                        new
                        {
                            IdEstado = (short)25,
                            Nome = "Paraíba",
                            Sigla = "PB"
                        },
                        new
                        {
                            IdEstado = (short)26,
                            Nome = "Pernambuco",
                            Sigla = "PE"
                        },
                        new
                        {
                            IdEstado = (short)27,
                            Nome = "Alagoas",
                            Sigla = "AL"
                        },
                        new
                        {
                            IdEstado = (short)28,
                            Nome = "Sergipe",
                            Sigla = "SE"
                        },
                        new
                        {
                            IdEstado = (short)29,
                            Nome = "Bahia",
                            Sigla = "BA"
                        },
                        new
                        {
                            IdEstado = (short)31,
                            Nome = "Minas Gerais",
                            Sigla = "MG"
                        },
                        new
                        {
                            IdEstado = (short)32,
                            Nome = "Espírito Santo",
                            Sigla = "ES"
                        },
                        new
                        {
                            IdEstado = (short)33,
                            Nome = "Rio de Janeiro",
                            Sigla = "RJ"
                        },
                        new
                        {
                            IdEstado = (short)35,
                            Nome = "São Paulo",
                            Sigla = "SP"
                        },
                        new
                        {
                            IdEstado = (short)41,
                            Nome = "Paraná",
                            Sigla = "PR"
                        },
                        new
                        {
                            IdEstado = (short)42,
                            Nome = "Santa Catarina",
                            Sigla = "SC"
                        },
                        new
                        {
                            IdEstado = (short)43,
                            Nome = "Rio Grande do Sul",
                            Sigla = "RS"
                        },
                        new
                        {
                            IdEstado = (short)50,
                            Nome = "Mato Grosso do Sul",
                            Sigla = "MS"
                        },
                        new
                        {
                            IdEstado = (short)51,
                            Nome = "Mato Grosso",
                            Sigla = "MT"
                        },
                        new
                        {
                            IdEstado = (short)52,
                            Nome = "Goiás",
                            Sigla = "GO"
                        },
                        new
                        {
                            IdEstado = (short)53,
                            Nome = "Distrito Federal",
                            Sigla = "DF"
                        });
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Instituicao", b =>
                {
                    b.Property<int>("IdInstituicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idInstituicao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInstituicao"));

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cep");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<TimeSpan>("HorarioFimAtendimento")
                        .HasColumnType("time")
                        .HasColumnName("horarioFimAtendimento");

                    b.Property<TimeSpan>("HorarioInicioAtendimento")
                        .HasColumnType("time")
                        .HasColumnName("horarioInicioAtendimento");

                    b.Property<int>("IdCidade")
                        .HasColumnType("int")
                        .HasColumnName("idCidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.HasKey("IdInstituicao");

                    b.HasIndex("IdCidade");

                    b.ToTable("Instituicao", (string)null);
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Pratica", b =>
                {
                    b.Property<short>("IdPratica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("idPratica");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("IdPratica"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.HasKey("IdPratica");

                    b.ToTable("Pratica", (string)null);
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.PraticaInstituicao", b =>
                {
                    b.Property<short>("IdPratica")
                        .HasColumnType("smallint")
                        .HasColumnName("idPratica");

                    b.Property<int>("IdInstituicao")
                        .HasColumnType("int")
                        .HasColumnName("idInstituicao");

                    b.Property<byte>("DiaPermitidoParaAgendamento")
                        .HasColumnType("tinyint")
                        .HasColumnName("diaPermitidoParaAgendamento");

                    b.Property<byte>("Periodicidade")
                        .HasColumnType("tinyint")
                        .HasColumnName("periodicidade");

                    b.Property<short>("QtdSessoes")
                        .HasColumnType("smallint")
                        .HasColumnName("qtdSessoes");

                    b.HasKey("IdPratica", "IdInstituicao");

                    b.HasIndex("IdInstituicao");

                    b.ToTable("PraticaInstituicao", (string)null);
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.TermoConsentimento", b =>
                {
                    b.Property<int>("IdAgendamento")
                        .HasColumnType("int")
                        .HasColumnName("idAgendamento");

                    b.Property<DateTime>("DataConsentimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataConsentimento");

                    b.HasKey("IdAgendamento");

                    b.ToTable("TermoConsentimento", (string)null);
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.TokenAcesso", b =>
                {
                    b.Property<int>("IdTokenAcesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTokenAcesso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTokenAcesso"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataExpiracao");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("token");

                    b.Property<bool>("Utilizado")
                        .HasColumnType("bit")
                        .HasColumnName("utilizado");

                    b.HasKey("IdTokenAcesso");

                    b.ToTable("TokenAcesso", (string)null);
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("FlPrimeiroAcesso")
                        .HasColumnType("bit")
                        .HasColumnName("flPrimeiroAcesso");

                    b.Property<int?>("IdInstituicao")
                        .HasColumnType("int")
                        .HasColumnName("idInstituicao");

                    b.Property<byte>("IdPerfil")
                        .HasColumnType("tinyint")
                        .HasColumnName("idPerfil");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("login");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("senha");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdInstituicao");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            FlPrimeiroAcesso = true,
                            IdPerfil = (byte)1,
                            Login = "admin",
                            Senha = "$2a$12$a0oXFr4B3AbjZk3sTh84Puq70PCBj9cf.iEIEm91aWvvnuLXh2Rfu"
                        });
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("AgendaPics.Domain.Entities.Instituicao", "Instituicao")
                        .WithMany("Agendamentos")
                        .HasForeignKey("IdInstituicao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendaPics.Domain.Entities.Pratica", "Pratica")
                        .WithMany()
                        .HasForeignKey("IdPratica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instituicao");

                    b.Navigation("Pratica");
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Atendimento", b =>
                {
                    b.HasOne("AgendaPics.Domain.Entities.Agendamento", "Agendamento")
                        .WithMany("Atendimentos")
                        .HasForeignKey("IdAgendamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agendamento");
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Avaliacao", b =>
                {
                    b.HasOne("AgendaPics.Domain.Entities.Atendimento", "Atendimento")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("IdAtendimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Cidade", b =>
                {
                    b.HasOne("AgendaPics.Domain.Entities.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Instituicao", b =>
                {
                    b.HasOne("AgendaPics.Domain.Entities.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("IdCidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.PraticaInstituicao", b =>
                {
                    b.HasOne("AgendaPics.Domain.Entities.Instituicao", "Instituicao")
                        .WithMany("PraticasInstituicoes")
                        .HasForeignKey("IdInstituicao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendaPics.Domain.Entities.Pratica", "Pratica")
                        .WithMany("PraticasInstituicoes")
                        .HasForeignKey("IdPratica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instituicao");

                    b.Navigation("Pratica");
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.TermoConsentimento", b =>
                {
                    b.HasOne("AgendaPics.Domain.Entities.Agendamento", "Agendamento")
                        .WithOne("TermoConsentimento")
                        .HasForeignKey("AgendaPics.Domain.Entities.TermoConsentimento", "IdAgendamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agendamento");
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("AgendaPics.Domain.Entities.Instituicao", "Instituicao")
                        .WithMany()
                        .HasForeignKey("IdInstituicao");

                    b.Navigation("Instituicao");
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Agendamento", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("TermoConsentimento");
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Atendimento", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Instituicao", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("PraticasInstituicoes");
                });

            modelBuilder.Entity("AgendaPics.Domain.Entities.Pratica", b =>
                {
                    b.Navigation("PraticasInstituicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
